### ISSUE TITLE
升级1.2后出现TypeError: removeConsole is not a function

### ISSUE THREAD

**Issue by MichaelLv0121** [xiaoxian521/vite-plugin-remove-console#10]
升级1.2后出现运行vite3.2.3，出现TypeError: removeConsole is not a function错误，项目无法运行。
![Snipaste_2022-11-09_10-34-39](https://user-images.githubusercontent.com/55915216/200723390-8958edb8-b2be-451f-9ba6-27be48a2edd2.png)

**Comment by xiaoxian521** [comment]
我认为 `vite` 3.1.8 之后存在很大问题，所以我建议你把vite版本固定到 `3.1.8 `，等vite 出 `4` 在升级

**Comment by MichaelLv0121** [comment]
> 我认为 `vite` 3.1.8 之后存在很大问题，所以我建议你把 `vite` 版本固定到 `3.1.8`，等vite 出 `4` 在升级

好的，感谢大佬

**Comment by xiaoxian521** [comment]
你 `vite` 改到3.1.8可以用了吗？

**Comment by xiaoxian521** [comment]
Upgrading to the latest version solves the problem
