### ISSUE TITLE
vite版本3.1.8以下仍然报错，提示TypeError: removeConsole is not a function

### ISSUE THREAD

**Issue by BRR-bupt** [xiaoxian521/vite-plugin-remove-console#11]
应该不是vite版本问题

**Comment by xiaoxian521** [comment]
给我个复现仓库吧我去调试看看

**Comment by BRR-bupt** [comment]
https://github.com/BRR-bupt/fixphone
在已有的项目（上述）中使用该插件报错，但我用官方模板新建项目引用该插件可以正常运行，还没找出问题点

**Comment by xiaoxian521** [comment]
应该是因为 `packag.json` 声明了 `"type": "module"` ，我处理下

**Comment by xiaoxian521** [comment]
upgrading to the latest version solves the problem
