### ISSUE TITLE
我想加一个选择。如果log中有指定的字符，则不删除

### ISSUE THREAD

**Issue by wChenonly** [xiaoxian521/vite-plugin-remove-console#12]
比如：
console.log('wf',123)
console.log(123)
只要log中含有wf。我就不删除

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/37658262/219285745-ff7595d5-3cb5-4e78-8af7-4af93e1b444d.png">

但是 我在处理ast的时候，
$T(source, { parseOptions: { sourceType: "module" } }).find(consoles)
我想先根据上面的返回值，解析出来 log中的value值。是否可行？
因为transform.js被压缩了 ，我看不到有哪些方法

**Comment by xiaoxian521** [comment]
The compression code is taken from [gogocode](https://github.com/thx/gogocode) Give you a URL https://juejin.cn/post/6943114726175932452 to watch
