### ISSUE TITLE
某些特殊场景删除console会导致代码报错，这个问题希望能修复一下

### ISSUE THREAD

**Issue by liaolongdong** [xiaoxian521/vite-plugin-remove-console#15]
https://github.com/xiaoxian521/vite-plugin-remove-console/issues/14
删除console.log不能影响业务代码，程序报错，这个问题感觉很严重？希望能够修复一下，不让不敢用，风险太大了

**Comment by xiaoxian521** [comment]
这个业务 代码自己处理 插件不管
