### ISSUE TITLE
是否支持删除指定的log类型

### ISSUE THREAD

**Issue by ZNN-She** [xiaoxian521/vite-plugin-remove-console#4]
是否支支持删除指定的log类型，例如
`include: ['log', 'warn']`

或者通过注释不删除某行log
`
// exclude log
console.log('这行不会被删除')
`

因为transform.js是被压缩过的，看不到源码

**Comment by xiaoxian521** [comment]
Yes, but I think warn and error if written should be what the user wants to be printed

**Comment by xiaoxian521** [comment]
Currently supported, please upgrade to the latest version
