### ISSUE TITLE
Problem when build: export { removeConsole as default }

### ISSUE THREAD

**Issue by VladimirCores** [xiaoxian521/vite-plugin-remove-console#9]
`"typescript": "^4.6.4",`
`"vite": "^3.2.0",`

![image](https://user-images.githubusercontent.com/442111/199972234-7a06fe4c-1718-4cd0-8690-2245cc245bcd.png)

Removing this line hels:
![image](https://user-images.githubusercontent.com/442111/199972450-a44e4d73-4ec3-4478-bd41-2c9b3427a0f8.png)

BTW: Useful plugin, thanks ; )

**Comment by xiaoxian521** [comment]
Hey, is it convenient to provide a reproduction warehouse, so that I can easily debug

**Comment by xiaoxian521** [comment]
Use `export default removeConsole;` instead of `export { removeConsole as default };`, maybe it will be fine. welcome pr 😊

**Comment by xiaoxian521** [comment]
Please upgrade to the latest version, it should be fixed
